UPDATE products SET inStock=78 WHERE name="TEMBO PRESSION";
UPDATE products SET inStock=30 WHERE name="LEGEND";
UPDATE products SET inStock=28 WHERE name="SODA";
UPDATE products SET inStock=30 WHERE name="BEAUFORT GRAND";
UPDATE products SET inStock=14 WHERE name="FANTA ORANGE";
UPDATE products SET inStock=25 WHERE name="Maltina";
UPDATE products SET inStock=47 WHERE name="BEAUFORT PETIT";
UPDATE products SET inStock=59 WHERE name="NKOYI";
UPDATE products SET inStock=15 WHERE name="VITALO";
UPDATE products SET inStock=0 WHERE name="VERRE DE JUS";
UPDATE products SET inStock=72 WHERE name="Mesure de DOUBLE BLACK";
UPDATE products SET inStock=14 WHERE name="BAVARIA";
UPDATE products SET inStock=25 WHERE name="Heineken Locale";
UPDATE products SET inStock=19 WHERE name="LEFFE BRUNE";
UPDATE products SET inStock=31 WHERE name="COCA EN BOUTEILLE";
UPDATE products SET inStock=14 WHERE name="XXL";
UPDATE products SET inStock=12 WHERE name="TURBO KING";
UPDATE products SET inStock=13 WHERE name="Duvel";
UPDATE products SET inStock=8 WHERE name="DUNHILL";
UPDATE products SET inStock=10 WHERE name="Energie Malt";
UPDATE products SET inStock=23 WHERE name="LEFFE BLONDE";
UPDATE products SET inStock=28 WHERE name="SAVANA";
UPDATE products SET inStock=43 WHERE name="Mesure de RED LABEL";
UPDATE products SET inStock=42 WHERE name="Shot de Olmeca Sivler";
UPDATE products SET inStock=13 WHERE name="AMBASSADE";
UPDATE products SET inStock=29 WHERE name="33 Export";
UPDATE products SET inStock=37 WHERE name="Bouteille Martell VS";
UPDATE products SET inStock=36 WHERE name="Mesure de GIN GORDON";
UPDATE products SET inStock=16 WHERE name="TONIC";
UPDATE products SET inStock=32 WHERE name="Mesure de Jack Daniel's #7";
UPDATE products SET inStock=41 WHERE name="CASTEL";
UPDATE products SET inStock=28 WHERE name="Shot de Olmeca Chocolate";
UPDATE products SET inStock=4 WHERE name="Primus La Petite";
UPDATE products SET inStock=25 WHERE name="Mesure de GIN BOMBAY";
UPDATE products SET inStock=24 WHERE name="Chivas 15 ans mesures";
UPDATE products SET inStock=24 WHERE name="Mesure d'Amarula";
UPDATE products SET inStock=24 WHERE name="Mesure de Baileys";
UPDATE products SET inStock=24 WHERE name="Mesure de Blue Label";
UPDATE products SET inStock=24 WHERE name="Mesure de CAPITAINE MORGAN";
UPDATE products SET inStock=24 WHERE name="Mesure de JAMSON";
UPDATE products SET inStock=24 WHERE name="Mesure de MALIBU";
UPDATE products SET inStock=7 WHERE name="EAU";
UPDATE products SET inStock=23 WHERE name="Mesure Martell Blue Swift";
UPDATE products SET inStock=22 WHERE name="Mesure de JACK DANIEL'S HONEY";
UPDATE products SET inStock=21 WHERE name="4 cousins strawberry hilles";
UPDATE products SET inStock=9 WHERE name="TEMBO BOUTEILLE";
UPDATE products SET inStock=14 WHERE name="Mesure de Campari";
UPDATE products SET inStock=14 WHERE name="Mesure de LIMONCELLO";
UPDATE products SET inStock=12 WHERE name="Baron d'Arignac Medium Sweet";
UPDATE products SET inStock=12 WHERE name="Mesure de Absolut VODKA";
UPDATE products SET inStock=12 WHERE name="Mesure de Bacardi Blanc";
UPDATE products SET inStock=12 WHERE name="Mesure de MARTINI BLANC";
UPDATE products SET inStock=11 WHERE name="CORONA";
UPDATE products SET inStock=4 WHERE name="REDBULL";
UPDATE products SET inStock=12 WHERE name="Mesure de Gold Label";
UPDATE products SET inStock=12 WHERE name="Mesure de Henessy VSOP";
UPDATE products SET inStock=11 WHERE name="Mesure de DISARONNO";
UPDATE products SET inStock=11 WHERE name="Mesure Martel VS";
UPDATE products SET inStock=7 WHERE name="Miel Naturel";
UPDATE products SET inStock=10 WHERE name="Chivas 12Y Mesures";
UPDATE products SET inStock=10 WHERE name="Mesure de COINTREAU";
UPDATE products SET inStock=9 WHERE name="Hunter’s";
UPDATE products SET inStock=9 WHERE name="Bouteille Sir Edward";
UPDATE products SET inStock=0 WHERE name="COCA ZERO";
UPDATE products SET inStock=8 WHERE name="Mesure Glenfiddish 12 ans";
UPDATE products SET inStock=7 WHERE name="Bouteille Signore Prosecco";
UPDATE products SET inStock=6 WHERE name="4 Cousins Sauvignon Blanc";
UPDATE products SET inStock=6 WHERE name="Baron Blanc de Blancs";
UPDATE products SET inStock=6 WHERE name="L.-E Cabernet Sauvignon";
UPDATE products SET inStock=6 WHERE name="L.-E Merlot";
UPDATE products SET inStock=6 WHERE name="MOET BRUT 75cl";
UPDATE products SET inStock=0 WHERE name="Guinness";
UPDATE products SET inStock=5 WHERE name="Bouteille de Black Label 37.5cl";
UPDATE products SET inStock=5 WHERE name="Bouteille de Red Label 37.5cl";
UPDATE products SET inStock=5 WHERE name="Mesure de HENNESSY VS";
UPDATE products SET inStock=4 WHERE name="Verre Gingembre";
UPDATE products SET inStock=4 WHERE name="4 Cousins Sauvignon Rouge";
UPDATE products SET inStock=3 WHERE name="4 Cousins Rouge Merlot";
UPDATE products SET inStock=3 WHERE name="Baron D'arignac rouge moelleux";
UPDATE products SET inStock=3 WHERE name="Bouteille de GIN BOMBAY 75cl";
UPDATE products SET inStock=3 WHERE name="L.-E Sauvignon Blanc";
UPDATE products SET inStock=3 WHERE name="Mesure Jack Daniel Single Barrel";
UPDATE products SET inStock=3 WHERE name="Sir Edward Smoky";
UPDATE products SET inStock=2 WHERE name="Baron D'arignac Rouge Sec";
UPDATE products SET inStock=2 WHERE name="Bouteille de DOUBLE BLACK 75cl";
UPDATE products SET inStock=2 WHERE name="Bouteille de JAMSON";
UPDATE products SET inStock=2 WHERE name="Bouteille Glenfiddich 15ans";
UPDATE products SET inStock=2 WHERE name="Mesure Triple Sec";
UPDATE products SET inStock=2 WHERE name="Ruinart Blanc de Blancs";
UPDATE products SET inStock=1 WHERE name="Bouteille de BLACK LABEL";
UPDATE products SET inStock=1 WHERE name="Bouteille de CHIVAS 12yrs";
UPDATE products SET inStock=1 WHERE name="Bouteille de CHIVAS 15ans";
UPDATE products SET inStock=1 WHERE name="Bouteille de GIN GORDON";
UPDATE products SET inStock=1 WHERE name="Bouteille de HENNESSY VS";
UPDATE products SET inStock=1 WHERE name="Bouteille de J&B";
UPDATE products SET inStock=1 WHERE name="Bouteille de JACK DANIEL'S HONEY";
UPDATE products SET inStock=1 WHERE name="Bouteille Glenfiddich 12ans";
UPDATE products SET inStock=1 WHERE name="Martini sans Alcool";
UPDATE products SET inStock=1 WHERE name="Papillon Brut";
UPDATE products SET inStock=1 WHERE name="Ruinart Petit Brut";
UPDATE products SET inStock=1 WHERE name="Ailes de poulet";
UPDATE products SET inStock=1 WHERE name="4 cousins marule";
UPDATE products SET inStock=0 WHERE name="4 Cousins Chardonnay Blanc";
UPDATE products SET inStock=0 WHERE name="4 Cousins Sweet White";
UPDATE products SET inStock=0 WHERE name="BARON ICE";
UPDATE products SET inStock=0 WHERE name="Bonobo KwiluRhum Mesures";
UPDATE products SET inStock=0 WHERE name="Bouteille de AMARULA";
UPDATE products SET inStock=0 WHERE name="Bouteille de BAILEYS";
UPDATE products SET inStock=0 WHERE name="Bouteille de CHIVAS 18ans";
UPDATE products SET inStock=0 WHERE name="Bouteille de Courvoisier";
UPDATE products SET inStock=0 WHERE name="Bouteille de MALIBU";
UPDATE products SET inStock=0 WHERE name="Bouteille de RED LABEL";
UPDATE products SET inStock=0 WHERE name="Bouteille Glenfiddich 18 yrs";
UPDATE products SET inStock=0 WHERE name="Bouteille Jack Daniels Gentleman 70 cl";
UPDATE products SET inStock=0 WHERE name="Bouteille Jack Daniels Single barrel";
UPDATE products SET inStock=0 WHERE name="Bouteille Johnny Walker Gold 75Cl";
UPDATE products SET inStock=0 WHERE name="Bouteille Martell Blue Swift";
UPDATE products SET inStock=0 WHERE name="Bouteille Sheridan's";
UPDATE products SET inStock=0 WHERE name="Champagne Mercier Brut";
UPDATE products SET inStock=0 WHERE name="Veuve Clicquot Brut";
UPDATE products SET inStock=0 WHERE name="Cognac Bisquit Mesure";
UPDATE products SET inStock=0 WHERE name="DON OSCART BLANC DE BLANC";
UPDATE products SET inStock=0 WHERE name="DON OSCART BRUT";
UPDATE products SET inStock=0 WHERE name="DON OSCART ROSEE";
UPDATE products SET inStock=0 WHERE name="LAGAVULIN Mesures";
UPDATE products SET inStock=0 WHERE name="Mesure de Bacardi Brun";
UPDATE products SET inStock=0 WHERE name="Mesure de Black Label";
UPDATE products SET inStock=0 WHERE name="Mesure de Cassis";
UPDATE products SET inStock=0 WHERE name="Mesure de Cinzano Bianco";
UPDATE products SET inStock=0 WHERE name="Mesure de GET 27";
UPDATE products SET inStock=0 WHERE name="Mesure de J&B";
UPDATE products SET inStock=0 WHERE name="Mesure de JAGERMEIFTER";
UPDATE products SET inStock=0 WHERE name="Mesure de MARTINI ROUGE";
UPDATE products SET inStock=0 WHERE name="Mesure de Sheridan's";
UPDATE products SET inStock=0 WHERE name="Mesure de TEQUILA Camilo";
UPDATE products SET inStock=0 WHERE name="Mesure Grundheim";
UPDATE products SET inStock=0 WHERE name="Mesures de Tequila Anejo Patron";
UPDATE products SET inStock=0 WHERE name="Mesures Glenfiddich 15ans";
UPDATE products SET inStock=0 WHERE name="Mesures Grand Marnier";
UPDATE products SET inStock=0 WHERE name="Mesures Grant's 1L";
UPDATE products SET inStock=0 WHERE name="Moet Brut Moyen";
UPDATE products SET inStock=0 WHERE name="MOET ICE";
UPDATE products SET inStock=0 WHERE name="Papillon Demi Sec";
UPDATE products SET inStock=0 WHERE name="Pierre Grandet";
UPDATE products SET inStock=0 WHERE name="Ruinart Brut";
UPDATE products SET inStock=0 WHERE name="Vin Baron d'arignac Sec";
UPDATE products SET inStock=0 WHERE name="Vin Blanc Domaine de Baume";
UPDATE products SET inStock=0 WHERE name="Vin Rouge Celier D'Or sec";
UPDATE products SET inStock=0 WHERE name="DOPPEL";
UPDATE products SET inStock=39 WHERE name="Heineken Importé";
UPDATE products SET inStock=1 WHERE name="Heineken Zéro";
UPDATE products SET inStock=7 WHERE name="MUTZIG";
UPDATE products SET inStock=3 WHERE name="NESPRESSO";
UPDATE products SET inStock=0 WHERE name="PRIMUS";
UPDATE products SET inStock=0 WHERE name="SKOL";
UPDATE products SET inStock=8 WHERE name="SPRITE";
UPDATE products SET inStock=6 WHERE name="STELLA ARTOIS";
UPDATE products SET inStock=3 WHERE name="THE";
UPDATE products SET inStock=0 WHERE name="ASSIETTE DE FROMAGE";
UPDATE products SET inStock=0 WHERE name="BANANE";
UPDATE products SET inStock=0 WHERE name="Banane Bouillie";
UPDATE products SET inStock=0 WHERE name="BAVETTE";
UPDATE products SET inStock=0 WHERE name="BOLOGNAISE";
UPDATE products SET inStock=0 WHERE name="Bouillon Makoso";
UPDATE products SET inStock=0 WHERE name="Bouillon Ntaba";
UPDATE products SET inStock=0 WHERE name="Boulette Viande";
UPDATE products SET inStock=0 WHERE name="Bout de Porc Fumé";
UPDATE products SET inStock=0 WHERE name="Brochettes 2 pcs";
UPDATE products SET inStock=0 WHERE name="Brochettes en plat";
UPDATE products SET inStock=0 WHERE name="Buffet Spécial";
UPDATE products SET inStock=0 WHERE name="COTE DE PORC";
UPDATE products SET inStock=0 WHERE name="Cailles";
UPDATE products SET inStock=0 WHERE name="Carbonade de Porc";
UPDATE products SET inStock=0 WHERE name="Champignons Frais";
UPDATE products SET inStock=0 WHERE name="CONTRE FILET";
UPDATE products SET inStock=0 WHERE name="COTE A L'OS";
UPDATE products SET inStock=0 WHERE name="COU PORC";
UPDATE products SET inStock=0 WHERE name="CROQUE MONSIEUR";
UPDATE products SET inStock=0 WHERE name="Demi Poulet Fume";
UPDATE products SET inStock=0 WHERE name="Dorade";
UPDATE products SET inStock=0 WHERE name="Emballage";
UPDATE products SET inStock=0 WHERE name="Epinard";
UPDATE products SET inStock=0 WHERE name="FRITES";
UPDATE products SET inStock=0 WHERE name="Fufu";
UPDATE products SET inStock=0 WHERE name="Gesiers de Poulet";
UPDATE products SET inStock=0 WHERE name="Gigot d'Agneau";
UPDATE products SET inStock=0 WHERE name="Gombo";
UPDATE products SET inStock=0 WHERE name="Grand Jambonneau";
UPDATE products SET inStock=0 WHERE name="Grand Nzanda braisé 3 pers";
UPDATE products SET inStock=0 WHERE name="Poisson Braisé Grand ";
UPDATE products SET inStock=0 WHERE name="Gros Jeune capitaine";
UPDATE products SET inStock=0 WHERE name="GUE";
UPDATE products SET inStock=0 WHERE name="Hamburger";
UPDATE products SET inStock=0 WHERE name="JAMBONNEAU";
UPDATE products SET inStock=0 WHERE name="Lapin";
UPDATE products SET inStock=0 WHERE name="Légume Mixtes";
UPDATE products SET inStock=0 WHERE name="Légume Vert";
UPDATE products SET inStock=0 WHERE name="Légumes verts et poisson fumé";
UPDATE products SET inStock=0 WHERE name="Liboke Poisson du Fleuve";
UPDATE products SET inStock=0 WHERE name="Liboke Filet Adal";
UPDATE products SET inStock=0 WHERE name="Lituma";
UPDATE products SET inStock=0 WHERE name="Malua";
UPDATE products SET inStock=0 WHERE name="Merguez 3 pcs";
UPDATE products SET inStock=0 WHERE name="Mpoka Moyen braisé pour 2 pers";
UPDATE products SET inStock=0 WHERE name="Mpose";
UPDATE products SET inStock=0 WHERE name="Ngolo Braisé";
UPDATE products SET inStock=0 WHERE name="Ngulu Braisé 500gr";
UPDATE products SET inStock=0 WHERE name="Nundu - Boss de Vache 500g";
UPDATE products SET inStock=0 WHERE name="Pilon Fumé";
UPDATE products SET inStock=0 WHERE name="Pilon de poulet";
UPDATE products SET inStock=0 WHERE name="Pilons panés";
UPDATE products SET inStock=0 WHERE name="Plat viande de Porc";
UPDATE products SET inStock=0 WHERE name="Poisson Braisé Moyen";
UPDATE products SET inStock=0 WHERE name="Poisson Filet de Capitaine";
UPDATE products SET inStock=0 WHERE name="Poisson fumé Mboto";
UPDATE products SET inStock=0 WHERE name="Poisson Jeune Capitaine";
UPDATE products SET inStock=0 WHERE name="Poisson Makayabu";
UPDATE products SET inStock=0 WHERE name="Poisson Braisé Petit";
UPDATE products SET inStock=0 WHERE name="Poisson Frais du Fleuve";
UPDATE products SET inStock=0 WHERE name="Poisson Perche";
UPDATE products SET inStock=0 WHERE name="Poisson Saumon";
UPDATE products SET inStock=0 WHERE name="Poisson Sole";
UPDATE products SET inStock=0 WHERE name="Poisson Tilapia";
UPDATE products SET inStock=0 WHERE name="Pomme de terre ";
UPDATE products SET inStock=0 WHERE name="Pondu";
UPDATE products SET inStock=0 WHERE name="Porc Braisé 500gr";
UPDATE products SET inStock=0 WHERE name="Porc sauce tomate";
UPDATE products SET inStock=0 WHERE name="Potage";
UPDATE products SET inStock=0 WHERE name="Poulet Entier";
UPDATE products SET inStock=0 WHERE name="Poulet Lumba Lumba";
UPDATE products SET inStock=0 WHERE name="Poussin";
UPDATE products SET inStock=0 WHERE name="Purée de pommes de terre";
UPDATE products SET inStock=0 WHERE name="RIZ";
UPDATE products SET inStock=0 WHERE name="SAMBAZA";
UPDATE products SET inStock=0 WHERE name="SAMOUSSA VIANDE";
UPDATE products SET inStock=0 WHERE name="Sauce aux Champignons";
UPDATE products SET inStock=0 WHERE name="SAUCISSE GOMA";
UPDATE products SET inStock=0 WHERE name="Saucisses Fraiches 2 pièces";
UPDATE products SET inStock=0 WHERE name="Saucisses piquantes Belgique";
UPDATE products SET inStock=0 WHERE name="Souris d'agneau";
UPDATE products SET inStock=0 WHERE name="Steak de Boeuf";
UPDATE products SET inStock=0 WHERE name="Tucha";
UPDATE products SET inStock=0 WHERE name="Chikwangue";
UPDATE products SET inStock=0 WHERE name="Cocktail Sans Alcool";
UPDATE products SET inStock=0 WHERE name="Cocktail avec Alcool";
UPDATE products SET inStock=8 WHERE name="Chica";
UPDATE products SET inStock=0 WHERE name="Menu Special";
UPDATE products SET inStock=0 WHERE name="Grand Tomahawk";
UPDATE products SET inStock=0 WHERE name="Moyen Tomahawk";
UPDATE products SET inStock=0 WHERE name="Petit Tomahawk";
UPDATE products SET inStock=0 WHERE name="Souris D'agneau";
UPDATE products SET inStock=0 WHERE name="L.-E Bordeaux Blanc";
UPDATE products SET inStock=0 WHERE name="Shot de Tequila Jose Cuervo";
UPDATE products SET inStock=0 WHERE name="Mesure de RICARD";
UPDATE products SET inStock=0 WHERE name="Pilau";
UPDATE products SET inStock=0 WHERE name="Barbecue à Volonté";
UPDATE products SET inStock=0 WHERE name="Ailes de Poulet Doux";
UPDATE products SET inStock=0 WHERE name="Bouillon de Bœuf";
UPDATE products SET inStock=0 WHERE name="Assiette 5 Mini Prochettes ";
UPDATE products SET inStock=0 WHERE name="Droit de bouchon";
UPDATE products SET inStock=0 WHERE name="Petits Poids Frais";
UPDATE products SET inStock=0 WHERE name="Filet Poisson façon Adal";
UPDATE products SET inStock=0 WHERE name="Coq au vin et champignon ";
UPDATE products SET inStock=0 WHERE name="Planche Mixte ";
UPDATE products SET inStock=0 WHERE name="Chèvre ";
UPDATE products SET inStock=0 WHERE name="Mitshopo sauté";
UPDATE products SET inStock=0 WHERE name="Cotis fumé";
UPDATE products SET inStock=0 WHERE name="Ntaba El Classico";
UPDATE products SET inStock=0 WHERE name="Côte d’Agneau";