UPDATE products SET inStock = 78 where name='TEMBO PRESSION';
UPDATE products SET inStock = 30 where name='LEGEND';
UPDATE products SET inStock = 28 where name='SODA';
UPDATE products SET inStock = 30 where name='BEAUFORT GRAND';
UPDATE products SET inStock = 14 where name='FANTA ORANGE';
UPDATE products SET inStock = 25 where name='Maltina';
UPDATE products SET inStock = 47 where name='BEAUFORT PETIT';
UPDATE products SET inStock = 59 where name='NKOYI';
UPDATE products SET inStock = 15 where name='VITALO';
UPDATE products SET inStock = 0 where name='VERRE DE JUS';
UPDATE products SET inStock = 14 where name='BAVARIA';
UPDATE products SET inStock = 25 where name='Heineken Locale';
UPDATE products SET inStock = 19 where name='LEFFE BRUNE';
UPDATE products SET inStock = 31 where name='COCA EN BOUTEILLE';
UPDATE products SET inStock = 14 where name='XXL';
UPDATE products SET inStock = 12 where name='TURBO KING';
UPDATE products SET inStock = 13 where name='Duvel';
UPDATE products SET inStock = 8 where name='DUNHILL';
UPDATE products SET inStock = 10 where name='Energie Malt';
UPDATE products SET inStock = 23 where name='LEFFE BLONDE';
UPDATE products SET inStock = 28 where name='SAVANA';
UPDATE products SET inStock = 13 where name='AMBASSADE';
UPDATE products SET inStock = 29 where name='33 Export';
UPDATE products SET inStock = 16 where name='TONIC';
UPDATE products SET inStock = 41 where name='CASTEL';
UPDATE products SET inStock = 4 where name='Primus La Petite';
UPDATE products SET inStock = 7 where name='EAU';
UPDATE products SET inStock = 9 where name='TEMBO BOUTEILLE';
UPDATE products SET inStock = 11 where name='CORONA';
UPDATE products SET inStock = 4 where name='REDBULL';
UPDATE products SET inStock = 7 where name='Miel Naturel';
UPDATE products SET inStock = 9 where name='Hunter’s';
UPDATE products SET inStock = 10 where name='Ailes de poulet';
UPDATE products SET inStock = 6 where name='ASSIETTE DE FROMAGE';
UPDATE products SET inStock = 3 where name='BANANE';
UPDATE products SET inStock = 0 where name='Banane Bouillie';
UPDATE products SET inStock = 0 where name='BAVETTE';
UPDATE products SET inStock = 0 where name='BOLOGNAISE';
UPDATE products SET inStock = 27 where name='Bouillon Makoso';
UPDATE products SET inStock = 9 where name='Bouillon Ntaba';
UPDATE products SET inStock = 0 where name='Boulette Viande';
UPDATE products SET inStock = 0 where name='Bout de Porc Fumé';
UPDATE products SET inStock = 0 where name='Brochettes 2 pcs';
UPDATE products SET inStock = 0 where name='Brochettes en plat';
UPDATE products SET inStock = 0 where name='Buffet Spécial';
UPDATE products SET inStock = 4 where name='COTE DE PORC';
UPDATE products SET inStock = 0 where name='Cailles';
UPDATE products SET inStock = 0 where name='Carbonade de Porc';
UPDATE products SET inStock = 4 where name='Champignons Frais';
UPDATE products SET inStock = 0 where name='CONTRE FILET';
UPDATE products SET inStock = 4 where name='COTE A L''OS';
UPDATE products SET inStock = 0 where name='COU PORC';
UPDATE products SET inStock = 0 where name='CROQUE MONSIEUR';
UPDATE products SET inStock = 0 where name='Demi Poulet Fume';
UPDATE products SET inStock = 0 where name='Dorade';
UPDATE products SET inStock = 6 where name='Emballage';
UPDATE products SET inStock = 6 where name='Epinard';
UPDATE products SET inStock = 10 where name='FRITES';
UPDATE products SET inStock = 10 where name='Fufu';
UPDATE products SET inStock = 18 where name='Gesiers de Poulet';
UPDATE products SET inStock = 0 where name='Gigot d''Agneau';
UPDATE products SET inStock = 0 where name='Gombo';
UPDATE products SET inStock = 0 where name='Grand Jambonneau';
UPDATE products SET inStock = 0 where name='Grand Nzanda braisé 3 pers';
UPDATE products SET inStock = 0 where name='Poisson Braisé Grand ';
UPDATE products SET inStock = 0 where name='Gros Jeune capitaine';
UPDATE products SET inStock = 0 where name='GUE';
UPDATE products SET inStock = 0 where name='Hamburger';
UPDATE products SET inStock = 0 where name='JAMBONNEAU';
UPDATE products SET inStock = 0 where name='Lapin';
UPDATE products SET inStock = 2 where name='Légume Mixtes';
UPDATE products SET inStock = 24 where name='Légume Vert';
UPDATE products SET inStock = 0 where name='Légumes verts et poisson fumé';
UPDATE products SET inStock = 0 where name='Liboke Poisson du Fleuve';
UPDATE products SET inStock = 0 where name='Liboke Filet Adal';
UPDATE products SET inStock = 4 where name='Lituma';
UPDATE products SET inStock = 0 where name='Malua';
UPDATE products SET inStock = 0 where name='Merguez 3 pcs';
UPDATE products SET inStock = 0 where name='Mpoka Moyen braisé pour 2 pers';
UPDATE products SET inStock = 0 where name='Mpose';
UPDATE products SET inStock = 0 where name='Ngolo Braisé';
UPDATE products SET inStock = 0 where name='Ngulu Braisé 500gr';
UPDATE products SET inStock = 0 where name='Nundu - Boss de Vache 500g';
UPDATE products SET inStock = 4 where name='Pilon Fumé';
UPDATE products SET inStock = 17 where name='Pilon de poulet';
UPDATE products SET inStock = 0 where name='Pilons panés';
UPDATE products SET inStock = 0 where name='Plat viande de Porc';
UPDATE products SET inStock = 0 where name='Poisson Braisé Moyen';
UPDATE products SET inStock = 0 where name='Poisson Filet de Capitaine';
UPDATE products SET inStock = 0 where name='Poisson fumé Mboto';
UPDATE products SET inStock = 0 where name='Poisson Jeune Capitaine';
UPDATE products SET inStock = 13 where name='Poisson Makayabu';
UPDATE products SET inStock = 0 where name='Poisson Braisé Petit';
UPDATE products SET inStock = 4 where name='Poisson Frais du Fleuve';
UPDATE products SET inStock = 0 where name='Poisson Perche';
UPDATE products SET inStock = 3 where name='Poisson Saumon';
UPDATE products SET inStock = 0 where name='Poisson Sole';
UPDATE products SET inStock = 0 where name='Poisson Tilapia';
UPDATE products SET inStock = 15 where name='Pomme de terre ';
UPDATE products SET inStock = 11 where name='Pondu';
UPDATE products SET inStock = 0 where name='Porc Braisé 500gr';
UPDATE products SET inStock = 0 where name='Porc sauce tomate';
UPDATE products SET inStock = 0 where name='Potage';
UPDATE products SET inStock = 5 where name='Poulet Entier';
UPDATE products SET inStock = 0 where name='Poulet Lumba Lumba';
UPDATE products SET inStock = 0 where name='Poussin';
UPDATE products SET inStock = 0 where name='Purée de pommes de terre';
UPDATE products SET inStock = 10 where name='RIZ';
UPDATE products SET inStock = 15 where name='SAMBAZA';
UPDATE products SET inStock = 35 where name='SAMOUSSA VIANDE';
UPDATE products SET inStock = 0 where name='Sauce aux Champignons';
UPDATE products SET inStock = 2 where name='SAUCISSE GOMA';
UPDATE products SET inStock = 2 where name='Saucisses Fraiches 2 pièces';
UPDATE products SET inStock = 0 where name='Saucisses piquantes Belgique';
UPDATE products SET inStock = 0 where name='Souris d''agneau';
UPDATE products SET inStock = 0 where name='Steak de Boeuf';
UPDATE products SET inStock = 0 where name='Tucha';
UPDATE products SET inStock = 43 where name='Chikwangue';
UPDATE products SET inStock = 0 where name='Menu Special';
UPDATE products SET inStock = 0 where name='Grand Tomahawk';
UPDATE products SET inStock = 0 where name='Moyen Tomahawk';
UPDATE products SET inStock = 0 where name='Petit Tomahawk';
UPDATE products SET inStock = 0 where name='Souris D''agneau';
UPDATE products SET inStock = 0 where name='Pilau';
UPDATE products SET inStock = 0 where name='Barbecue à Volonté';
UPDATE products SET inStock = 0 where name='Ailes de Poulet Doux';
UPDATE products SET inStock = 2 where name='Bouillon de Bœuf';
UPDATE products SET inStock = 0 where name='Assiette 5 Mini Prochettes ';
UPDATE products SET inStock = 1 where name='Petits Poids Frais';
UPDATE products SET inStock = 3 where name='Filet Poisson façon Adal';
UPDATE products SET inStock = 0 where name='Coq au vin et champignon ';
UPDATE products SET inStock = 0 where name='Planche Mixte ';
UPDATE products SET inStock = 0 where name='Chèvre ';
UPDATE products SET inStock = 0 where name='Mitshopo sauté';
UPDATE products SET inStock = 12 where name='Cotis fumé';
UPDATE products SET inStock = 0 where name='Ntaba El Classico';
UPDATE products SET inStock = 0 where name='Côte d’Agneau';
UPDATE products SET inStock = 28 where name='Mesure de DOUBLE BLACK';
UPDATE products SET inStock = 46 where name='Mesure de RED LABEL';
UPDATE products SET inStock = 20 where name='Shot de Olmeca Sivler';
UPDATE products SET inStock = 0 where name='Bouteille Martell VS';
UPDATE products SET inStock = 10 where name='Mesure de GIN GORDON';
UPDATE products SET inStock = 12 where name='Mesure de Jack Daniel''s #7';
UPDATE products SET inStock = 16 where name='Shot de Olmeca Chocolate';
UPDATE products SET inStock = 5 where name='Mesure de GIN BOMBAY';
UPDATE products SET inStock = 13 where name='Chivas 15 ans mesures';
UPDATE products SET inStock = 23 where name='Mesure d''Amarula';
UPDATE products SET inStock = 15 where name='Mesure de Baileys';
UPDATE products SET inStock = 10 where name='Mesure de Blue Label';
UPDATE products SET inStock = 4 where name='Mesure de CAPITAINE MORGAN';
UPDATE products SET inStock = 21 where name='Mesure de JAMSON';
UPDATE products SET inStock = 20 where name='Mesure de MALIBU';
UPDATE products SET inStock = 11 where name='Mesure Martell Blue Swift';
UPDATE products SET inStock = 10 where name='Mesure de JACK DANIEL''S HONEY';
UPDATE products SET inStock = 1 where name='4 cousins strawberry hilles';
UPDATE products SET inStock = 14 where name='Mesure de Campari';
UPDATE products SET inStock = 6 where name='Mesure de LIMONCELLO';
UPDATE products SET inStock = 2 where name='Baron d''Arignac Medium Sweet';
UPDATE products SET inStock = 2 where name='Mesure de Absolut VODKA';
UPDATE products SET inStock = 2 where name='Mesure de Bacardi Blanc';
UPDATE products SET inStock = 18 where name='Mesure de MARTINI BLANC';
UPDATE products SET inStock = 10 where name='Mesure de Gold Label';
UPDATE products SET inStock = 17 where name='Mesure de Henessy VSOP';
UPDATE products SET inStock = 10 where name='Mesure de DISARONNO';
UPDATE products SET inStock = 16 where name='Mesure Martel VS';
UPDATE products SET inStock = 12 where name='Chivas 12Y Mesures';
UPDATE products SET inStock = 4 where name='Mesure de COINTREAU';
UPDATE products SET inStock = 1 where name='Bouteille Sir Edward';
UPDATE products SET inStock = 13 where name='Mesure Glenfiddish 12 ans';
UPDATE products SET inStock = 2 where name='Bouteille Signore Prosecco';
UPDATE products SET inStock = 2 where name='4 Cousins Sauvignon Blanc';
UPDATE products SET inStock = 3 where name='Baron Blanc de Blancs';
UPDATE products SET inStock = 5 where name='L.-E Cabernet Sauvignon';
UPDATE products SET inStock = 6 where name='L.-E Merlot';
UPDATE products SET inStock = 1 where name='MOET BRUT 75cl';
UPDATE products SET inStock = 2 where name='Bouteille de Black Label 37.5cl';
UPDATE products SET inStock = 2 where name='Bouteille de Red Label 37.5cl';
UPDATE products SET inStock = 15 where name='Mesure de HENNESSY VS';
UPDATE products SET inStock = 1 where name='4 Cousins Sauvignon Rouge';
UPDATE products SET inStock = 1 where name='4 Cousins Rouge Merlot';
UPDATE products SET inStock = 0 where name='Baron D''arignac rouge moelleux';
UPDATE products SET inStock = 0 where name='Bouteille de GIN BOMBAY 75cl';
UPDATE products SET inStock = 3 where name='L.-E Sauvignon Blanc';
UPDATE products SET inStock = 0 where name='Mesure Jack Daniel Single Barrel';
UPDATE products SET inStock = 0 where name='Sir Edward Smoky';
UPDATE products SET inStock = 0 where name='Baron D''arignac Rouge Sec';
UPDATE products SET inStock = 0 where name='Bouteille de DOUBLE BLACK 75cl';
UPDATE products SET inStock = 0 where name='Bouteille de JAMSON';
UPDATE products SET inStock = 0 where name='Bouteille Glenfiddich 15ans';
UPDATE products SET inStock = 10 where name='Mesure Triple Sec';
UPDATE products SET inStock = 3 where name='Ruinart Blanc de Blancs';
UPDATE products SET inStock = 0 where name='Bouteille de BLACK LABEL';
UPDATE products SET inStock = 0 where name='Bouteille de CHIVAS 12yrs';
UPDATE products SET inStock = 0 where name='Bouteille de CHIVAS 15ans';
UPDATE products SET inStock = 0 where name='Bouteille de GIN GORDON';
UPDATE products SET inStock = 0 where name='Bouteille de HENNESSY VS';
UPDATE products SET inStock = 0 where name='Bouteille de J&B';
UPDATE products SET inStock = 0 where name='Bouteille de JACK DANIEL''S HONEY';
UPDATE products SET inStock = 0 where name='Bouteille Glenfiddich 12ans';
UPDATE products SET inStock = 1 where name='Martini sans Alcool';
UPDATE products SET inStock = 0 where name='Papillon Brut';
UPDATE products SET inStock = 0 where name='Ruinart Petit Brut';
UPDATE products SET inStock = 2 where name='4 cousins marule';
UPDATE products SET inStock = 0 where name='4 Cousins Chardonnay Blanc';
UPDATE products SET inStock = 4 where name='4 Cousins Sweet White';
UPDATE products SET inStock = 5 where name='BARON ICE';
UPDATE products SET inStock = 2 where name='Bonobo KwiluRhum Mesures';
UPDATE products SET inStock = 0 where name='Bouteille de AMARULA';
UPDATE products SET inStock = 0 where name='Bouteille de BAILEYS';
UPDATE products SET inStock = 1 where name='Bouteille de CHIVAS 18ans';
UPDATE products SET inStock = 0 where name='Bouteille de Courvoisier';
UPDATE products SET inStock = 0 where name='Bouteille de MALIBU';
UPDATE products SET inStock = 0 where name='Bouteille de RED LABEL';
UPDATE products SET inStock = 2 where name='Bouteille Glenfiddich 18 yrs';
UPDATE products SET inStock = 2 where name='Bouteille Jack Daniels Gentleman 70 cl';
UPDATE products SET inStock = 0 where name='Bouteille Jack Daniels Single barrel';
UPDATE products SET inStock = 0 where name='Bouteille Johnny Walker Gold 75Cl';
UPDATE products SET inStock = 0 where name='Bouteille Martell Blue Swift';
UPDATE products SET inStock = 0 where name='Bouteille Sheridan''s';
UPDATE products SET inStock = 0 where name='Champagne Mercier Brut';
UPDATE products SET inStock = 3 where name='Veuve Clicquot Brut';
UPDATE products SET inStock = 0 where name='Cognac Bisquit Mesure';
UPDATE products SET inStock = 0 where name='DON OSCART BLANC DE BLANC';
UPDATE products SET inStock = 1 where name='DON OSCART BRUT';
UPDATE products SET inStock = 0 where name='DON OSCART ROSEE';
UPDATE products SET inStock = 0 where name='LAGAVULIN Mesures';
UPDATE products SET inStock = 0 where name='Mesure de Bacardi Brun';
UPDATE products SET inStock = 28 where name='Mesure de Black Label';
UPDATE products SET inStock = 5 where name='Mesure de Cassis';
UPDATE products SET inStock = 6 where name='Mesure de Cinzano Bianco';
UPDATE products SET inStock = 0 where name='Mesure de GET 27';
UPDATE products SET inStock = 22 where name='Mesure de J&B';
UPDATE products SET inStock = 11 where name='Mesure de JAGERMEIFTER';
UPDATE products SET inStock = 17 where name='Mesure de MARTINI ROUGE';
UPDATE products SET inStock = 5 where name='Mesure de Sheridan''s';
UPDATE products SET inStock = 29 where name='Mesure de TEQUILA Camilo';
UPDATE products SET inStock = 0 where name='Mesure Grundheim';
UPDATE products SET inStock = 14 where name='Mesures de Tequila Anejo Patron';
UPDATE products SET inStock = 20 where name='Mesures Glenfiddich 15ans';
UPDATE products SET inStock = 6 where name='Mesures Grand Marnier';
UPDATE products SET inStock = 2 where name='Mesures Grant''s 1L';
UPDATE products SET inStock = 2 where name='Moet Brut Moyen';
UPDATE products SET inStock = 2 where name='MOET ICE';
UPDATE products SET inStock = 0 where name='Papillon Demi Sec';
UPDATE products SET inStock = 0 where name='Pierre Grandet';
UPDATE products SET inStock = 0 where name='Ruinart Brut';
UPDATE products SET inStock = 0 where name='Vin Baron d''arignac Sec';
UPDATE products SET inStock = 0 where name='Vin Blanc Domaine de Baume';
UPDATE products SET inStock = 0 where name='Vin Rouge Celier D''Or sec';
UPDATE products SET inStock = 5 where name='Cocktail Sans Alcool';
UPDATE products SET inStock = 6 where name='Cocktail avec Alcool';
UPDATE products SET inStock = 0 where name='L.-E Bordeaux Blanc';
UPDATE products SET inStock = 0 where name='Shot de Tequila Jose Cuervo';
UPDATE products SET inStock = 4 where name='Mesure de RICARD';
UPDATE products SET inStock = 6 where name='Droit de bouchon';
