INSERT INTO products SET categoryId=3, categoryName='Plat', name="Ailes de poulet", unit='-', isSellable = 1, isVersatile = 0, price = 7.5, buyPrice = 0, inStock = 12, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="ASSIETTE DE FROMAGE", unit='-', isSellable = 1, isVersatile = 0, price = 5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="BANANE", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 7, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Banane Bouillie", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="BAVETTE", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 11, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="BOLOGNAISE", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 7, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Bouillon Makoso", unit='-', isSellable = 1, isVersatile = 0, price = 5, buyPrice = 0, inStock = 24, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Bouillon Ntaba", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Boulette Viande", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Bout de Porc Fumé", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Brochettes 2 pcs", unit='-', isSellable = 1, isVersatile = 0, price = 7.5, buyPrice = 0, inStock = 11, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Brochettes en plat", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Buffet Spécial", unit='-', isSellable = 1, isVersatile = 0, price = 25, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="COTE DE PORC", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 7, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Cailles", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Carbonade de Porc", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 10, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Champignons Frais", unit='-', isSellable = 1, isVersatile = 0, price = 2.5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="CONTRE FILET", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="COTE A L'OS", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="COU PORC", unit='-', isSellable = 1, isVersatile = 0, price = 8, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="CROQUE MONSIEUR", unit='-', isSellable = 1, isVersatile = 0, price = 4, buyPrice = 0, inStock = 6, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Demi Poulet Fume", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Dorade", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Emballage", unit='-', isSellable = 1, isVersatile = 0, price = 1, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Epinard", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 9, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Filet pur de Boeuf", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="FRITES", unit='-', isSellable = 1, isVersatile = 0, price = 3, buyPrice = 0, inStock = 54, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Fufu", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 34, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Gesiers de Poulet", unit='-', isSellable = 1, isVersatile = 0, price = 7.5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Gigot d'Agneau", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Gombo", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Grand Jambonneau", unit='-', isSellable = 1, isVersatile = 0, price = 25, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Grand Nzanda braisé 3 pers", unit='-', isSellable = 1, isVersatile = 0, price = 45, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Grand Poisson Braisé", unit='-', isSellable = 1, isVersatile = 0, price = 45, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Gros Jeune capitaine", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="GUE", unit='-', isSellable = 1, isVersatile = 0, price = 1, buyPrice = 0, inStock = 4, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Hamburger", unit='-', isSellable = 1, isVersatile = 0, price = 7, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="JAMBONNEAU", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Jambonneau Fumé", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Lapin", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Légume Mixtes", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Légumes verts", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 9, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Légumes verts et poisson fumé", unit='-', isSellable = 1, isVersatile = 0, price = 4, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="LIBOKE", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Liboke de Mboto", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Liboke de Monganza", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Liboke de Mosombo", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Liboke de Mpoka", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Liboke de Mpose", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Liboke de Mungusu", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Liboke de Nzanda", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="LIBOKE MBIKA", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Lituma", unit='-', isSellable = 1, isVersatile = 0, price = 3, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Malua", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Mercredi poisson Spécial", unit='-', isSellable = 1, isVersatile = 0, price = 12.5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Merguez 3 pcs", unit='-', isSellable = 1, isVersatile = 0, price = 5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Moyen Poisson Braisé", unit='-', isSellable = 1, isVersatile = 0, price = 30, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Mpoka Moyen braisé pour 2 pers", unit='-', isSellable = 1, isVersatile = 0, price = 30, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Mpose", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Ngolo Braisé", unit='-', isSellable = 1, isVersatile = 0, price = 30, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Ngulu Braisé 500gr", unit='-', isSellable = 1, isVersatile = 0, price = 6, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Nundu - Boss de Vache 500g", unit='-', isSellable = 1, isVersatile = 0, price = 12, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Petit Poisson Braisé", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Pillon Fumé", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Pilon de poulet", unit='-', isSellable = 1, isVersatile = 0, price = 7.5, buyPrice = 0, inStock = 6, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Pilons panés", unit='-', isSellable = 1, isVersatile = 0, price = 9, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Plat viande de Porc", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Bar", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Braisé", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Filet de Capitaine", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson fumé Mboto", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Jeune Capitaine", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 8, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Makayabu", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 16, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Malwa", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Mbenga", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Mboto", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Merou", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Monganza", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Morue", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Mosombo", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 8, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Mosombo grand Braisé", unit='-', isSellable = 1, isVersatile = 0, price = 30, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Mosombo moyen  braisé", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Mosombo petit braisé", unit='-', isSellable = 1, isVersatile = 0, price = 12.5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson MPoka", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 20, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson MPoka braisé 1 pers", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson MPoka petit braisé", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Mungusu", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Nkamba", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Nzanda", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Nzanda braisé 1 pers", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Nzanda braisé 2 pers", unit='-', isSellable = 1, isVersatile = 0, price = 30, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Perche", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Perche gros", unit='-', isSellable = 1, isVersatile = 0, price = 30, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Saumon", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Sole", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poisson Tilapia", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 3, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Pomme de terre", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 16, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Pomme de terre Frites", unit='-', isSellable = 1, isVersatile = 0, price = 3, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="PONDU", unit='-', isSellable = 1, isVersatile = 0, price = 2, buyPrice = 0, inStock = 33, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Porc Braisé 500gr", unit='-', isSellable = 1, isVersatile = 0, price = 6, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Porc sauce tomate", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Potage", unit='-', isSellable = 1, isVersatile = 0, price = 5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poulet Entier", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 13, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poulet Lumba Lumba", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Poussin", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 2, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Purée de pommes de terre", unit='-', isSellable = 1, isVersatile = 0, price = 4, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="RIZ", unit='-', isSellable = 1, isVersatile = 0, price = 3, buyPrice = 0, inStock = 9, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="SAMBAZA", unit='-', isSellable = 1, isVersatile = 0, price = 5, buyPrice = 0, inStock = 13, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="SAMOUSSA VIANDE", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 42, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Sauce aux Champignons", unit='-', isSellable = 1, isVersatile = 0, price = 3, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="SAUCISSE GOMA", unit='-', isSellable = 1, isVersatile = 0, price = 7.5, buyPrice = 0, inStock = 32, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Saucisses Fraiches 2 pièces", unit='-', isSellable = 1, isVersatile = 0, price = 10, buyPrice = 0, inStock = 6, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Saucisses piquantes Belgique", unit='-', isSellable = 1, isVersatile = 0, price = 7.5, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Souris d'agneau", unit='-', isSellable = 1, isVersatile = 0, price = 20, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Steak de boeuf", unit='-', isSellable = 1, isVersatile = 0, price = 15, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Tomahawk", unit='-', isSellable = 1, isVersatile = 0, price = 30, buyPrice = 0, inStock = 0, timestamp = 1709475989;
INSERT INTO products SET categoryId=3, categoryName='Plat', name="Tucha", unit='-', isSellable = 1, isVersatile = 0, price = 7, buyPrice = 0, inStock = 0, timestamp = 1709475989;
